# Generated by Django 2.0.1 on 2018-12-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181202_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
