# Generated by Django 2.0.1 on 2018-12-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Good',
        ),
    ]
