# Generated by Django 2.0.1 on 2018-12-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181213_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='cat',
        ),
        migrations.AddField(
            model_name='good',
            name='type',
            field=models.CharField(default='10W-40', max_length=40, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='good',
            name='volume',
            field=models.CharField(default='1', max_length=3, verbose_name='Объем'),
        ),
    ]
