# Generated by Django 2.0.1 on 2019-01-17 10:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181217_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
