# Generated by Django 2.0.1 on 2019-01-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190117_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефонный номер')),
                ('mail', models.CharField(max_length=60, verbose_name='Email')),
                ('adress', models.CharField(max_length=400, verbose_name='Адрес')),
                ('description', models.CharField(max_length=1000, verbose_name='Комментарий к заказу')),
            ],
        ),
    ]
