# Generated by Django 2.0.1 on 2019-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(blank=True, choices=[('On', 'Безналичными'), ('Off', 'Наличными')], max_length=40),
        ),
    ]
