# Generated by Django 2.0.1 on 2019-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orders_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='cat',
            field=models.CharField(blank=True, choices=[('Oil', 'Моторное масло'), ('transmission', 'Трансмиссия'), ('Mototechnic', 'Мототехника'), ('Technical', 'Технические жидкости'), ('Lubricants', 'Смазки')], max_length=40),
        ),
        migrations.AlterField(
            model_name='good',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='good',
            name='viscosity',
            field=models.CharField(blank=True, max_length=40, verbose_name='Вязкость'),
        ),
        migrations.AlterField(
            model_name='good',
            name='volume',
            field=models.CharField(blank=True, default='1', max_length=3, verbose_name='Объем'),
        ),
    ]
