# Generated by Django 2.0.1 on 2019-02-09 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190208_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
