# Generated by Django 2.0.1 on 2019-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orders_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='cost',
            field=models.IntegerField(default='0', verbose_name='Цена'),
        ),
    ]
