# Generated by Django 2.0.1 on 2019-02-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190209_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='tec_category',
            field=models.CharField(blank=True, choices=[('Oil', 'Моторное масло'), ('transmission', 'Трансмиссия'), ('Mototechnic', 'Мототехника'), ('Technical', 'Технические жидкости'), ('Lubricants', 'Смазки')], max_length=40, verbose_name='Категория для технических жидкостей'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat',
            field=models.CharField(blank=True, choices=[('Oil', 'Моторное масло'), ('transmission', 'Трансмиссия'), ('Mototechnic', 'Мототехника'), ('Technical', 'Технические жидкости'), ('Lubricants', 'Смазки')], max_length=40, verbose_name='Категория'),
        ),
    ]
