# Generated by Django 2.0.1 on 2019-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190220_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='tec_category',
            field=models.CharField(blank=True, choices=[('Cleaners', 'Очистители'), ('Antifreeze', 'Антифриз'), ('Antikor', 'Антикор'), ('Brake_fluids', 'Тормозные жидкости')], max_length=40, verbose_name='Категория для технических жидкостей'),
        ),
    ]
